### ISSUE TITLE
Android 4.4 + 出现回调问题，是JavaScript的回调，不是Native的回调

### ISSUE THREAD

**Issue by ggYancey** [iazrael/AndroidJavascriptBridge#1]
jsb.require('messagebox', {'text': '你好, messagebox!'}, function(response){
            alert('调用messagebox回来啦\n' + JSON.stringify(response));
        });

调用完Java代码后，alert('调用messagebox回来啦\n' + JSON.stringify(response));方法不执行，但是在2.3的系统上面alert('调用messagebox回来啦\n' + JSON.stringify(response));是执行的。

**Comment by iazrael** [comment]
android 4.4是需要显式声明java方法支持被js调用才行的，需要使用一个@JavaScriptinterface的注解，建议你改造一下，^_^。
